//! Generates a **search-derived value corpus** from `mcts-value` self-play:
//! per decision, the win probability the search itself backed up at its root,
//! together with enough information to reconstruct the exact position it was
//! looking at.
//!
//! This is `value_corpus.rs`'s twin, not a generalization of it:
//! `docs/conventions.md`'s "agent crates are self-contained" pattern already
//! makes hand-duplicating an agent-specific tool the accepted move in this
//! project (see `mcts-value`'s own crate docs on why it copies `mcts-eval`'s
//! search rather than depending on it), and the two generators differ only in
//! which agent plays both seats and in the doc comments — parametrizing one
//! binary over an arbitrary agent name would have meant threading
//! `Box<dyn Agent>` through `last_root`'s typed `RootStats` accessor, which
//! neither agent's `Agent` trait exposes. A twin file is the smaller, more
//! honest change.
//!
//! Written for the corpus-generalization task: the shipped `duels-value`
//! weights were trained entirely on `mcts-eval` self-play
//! (`value_corpus.rs`), and the working theory under test is that a corpus
//! generated by the **champion agent itself** (`mcts-value`, `nodes:2000`) —
//! optionally mixed with a fresh `mcts-eval` batch as insurance against the
//! new corpus narrowing around `mcts-value`'s own blind spots — retrains into
//! a value function whose strength generalizes past the one opponent
//! (`mcts-eval`) the original corpus ever saw.
//!
//! Everything below is otherwise identical to `value_corpus.rs`: same JSONL
//! `GameLine`/`Decision` schema, same manifest sidecar, same `(seed, actions)`
//! replay key, same `--verify`. `feature_dump.rs` reads this format
//! agent-agnostically (it parses `GameLine`, not anything that names an
//! agent), so a corpus from this file plugs into the existing training
//! pipeline unmodified.
//!
//! ```text
//! # a small sample, with the built-in consistency check
//! cargo run --release -p duels-arena --example value_corpus_mv -- \
//!     --games 200 --seed 1 --out arena/corpus/sample-mv.jsonl
//! cargo run --release -p duels-arena --example value_corpus_mv -- \
//!     --verify arena/corpus/sample-mv.jsonl
//!
//! # a real run
//! cargo run --release -p duels-arena --example value_corpus_mv -- \
//!     --games 20000 --seed 1 --budget nodes:2000 \
//!     --out arena/corpus/mcts-value-nodes2000.jsonl
//! ```
//!
//! `arena/corpus/` is gitignored, following `arena/results/`: a corpus is a
//! regenerable data artifact, and only the generator belongs in the
//! repository.
//!
//! **Seed hygiene.** A game's seed is its identity here, so a training corpus
//! and anything used to check a model fitted on it must not share seeds.
//! `value_corpus.rs`'s original `mcts-eval` corpus used seeds `1..=100000`
//! with sanity-check samples at `800001` and `900001`; this generator's own
//! run documents whichever disjoint seed range it actually used in the PR
//! that adds the corpus, so as not to collide with either.
//!
//! # Why `(seed, actions)` and not a pile of positions
//!
//! Identical reasoning to `value_corpus.rs`: `docs/rules-spec.md`'s **R-108**
//! makes the engine deterministic given `(seed, actions)`, replay is five
//! orders of magnitude cheaper than the search that produced the labels, and
//! the one thing replay cannot recover — the search's own backed-up value —
//! is the only thing stored per decision.
//!
//! ## The exact replay recipe
//!
//! ```text
//! let mut state = engine::new_game(seed);
//! let mut rng   = StdRng::seed_from_u64(seed ^ ENGINE_RNG_SALT);
//! for action in actions { engine::apply(&mut state, action, &mut rng)?; }
//! ```
//!
//! `ENGINE_RNG_SALT` (`0x9E37_79B9_7F4A_7C15`) is the same convention
//! `value_corpus.rs`, `duels-server`'s `Room::new` and `duels-arena`'s
//! `match_runner` all use.
//!
//! # The format
//!
//! Byte-for-byte the same schema as `value_corpus.rs` produces — see that
//! file's module docs for the full field-by-field description of `GameLine`,
//! `Decision` and the manifest. The only difference here is which agent's
//! search produced `value`/`visits`/`policy`: `mcts-value`'s pure learned
//! leaf (no rollout, no `duels-eval` blend) rather than `mcts-eval`'s
//! half-playout-half-`duels-eval` leaf. That distinction matters for anyone
//! fitting against this corpus:
//!
//! # What `value` contains here — read this before fitting anything
//!
//! At `mcts-value::Config::default`, the leaf **is** `duels_value`'s own
//! learned four-way outcome model — there is no playout mixed in at all. So a
//! net retrained against this corpus's root values is fitting **its own prior
//! generation's opinion**, refined by 2000 nodes of tree search, rather than
//! against a search whose leaf came from somewhere independent (as
//! `mcts-eval`'s `duels-eval` blend was). This is exactly the
//! self-referential-bootstrap concern the task that produced this file
//! flagged as a reason to also keep a fresh `mcts-eval`-generated batch in
//! the mix: a corpus generated *purely* by the model being retrained risks
//! amplifying its own blind spots (a spot the old model never explored ends
//! up with no representation in the new corpus either, since search steers
//! away from what it already undervalues). The generated corpus's own
//! provenance note (this run's manifest, and the PR body that reports on it)
//! records whether a mixed batch was actually used and why.
//!
//! # Cost
//!
//! `mcts-value`'s leaf has no rollout (see its crate docs: "no playout at
//! all"), so its per-simulation cost should differ from `mcts-eval`'s
//! half-playout leaf — plausibly cheaper per node (no random playout to run
//! to completion) but with a fixed per-leaf inference cost `mcts-eval`
//! doesn't pay. Measure before committing to a games count; do not assume
//! `value_corpus.rs`'s measured 8.2 games/s / 204.5 min-per-100k transfers
//! unchanged. The manifest this tool writes after every batch records the
//! actual wall time, exactly like the original.
use std::fs::{self, File};
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::path::{Path, PathBuf};

use duels_agent_mcts_value::{Config as MctsValueConfig, MctsValueAgent};
use duels_agents_api::{Agent, AgentSpec, Budget};
use duels_arena::agent_spec::parse_mcts_value_config;
use duels_arena::match_runner::parse_budget;
use duels_core::{engine, Action, GameResult, Player};
use rand::{rngs::StdRng, SeedableRng};
use rayon::prelude::*;
use serde::{Deserialize, Serialize};

/// Salt for the engine's own mid-game RNG (The Great Library's token draw),
/// matching `duels-arena::match_runner` and `duels-server::room::Room::new`.
/// A replay must use it or a game containing a Great Library will diverge.
const ENGINE_RNG_SALT: u64 = 0x9E37_79B9_7F4A_7C15;

/// Per-seat agent RNG salts, so the two sides of a self-play game make
/// independent random choices from the same game seed. Recorded in the
/// manifest because they are what makes a *regeneration* reproduce a corpus
/// (a *replay* needs only the seed and the actions).
const SEAT_ONE_SALT: u64 = 0xA011_7A9E_5B21_0001;
const SEAT_TWO_SALT: u64 = 0xB022_8C3F_6D42_0002;

/// How many seeds one rayon batch covers. Bounds peak memory and gives the
/// progress line something to report; has no effect on the output.
const BATCH: usize = 256;

/// One searched decision: what the search concluded, and where it was.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct Decision {
    /// Index into the game's `actions`, so a skipped (forced) ply is visible
    /// as a gap rather than inferred.
    ply: u32,
    /// Whose decision it was.
    mover: Player,
    /// The root's backed-up win probability, from `Player::One`'s perspective.
    value: f64,
    /// Root visits the search actually spent (close to, not exactly, the node
    /// budget).
    visits: u64,
    /// Index into `engine::legal_actions` at this ply of the action played.
    chosen: usize,
    /// Root visit count per legal action, in `engine::legal_actions` order.
    #[serde(skip_serializing_if = "Option::is_none")]
    policy: Option<Vec<u32>>,
}

/// One self-play game: the replay key, the outcome, and the labels.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GameLine {
    seed: u64,
    moves: u32,
    result: GameResult,
    actions: Vec<Action>,
    decisions: Vec<Decision>,
}

/// The sidecar that makes a corpus file self-describing.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct Manifest {
    kind: String,
    version: u32,
    generated_by: String,
    /// The agent that played both seats, including the whole
    /// `duels-value`/weights configuration its leaves were scored against —
    /// `mcts-value` tracks `duels_value::default_weights_id()` live, so this
    /// string is the only thing that makes two corpora from either side of a
    /// weights retrain distinguishable.
    agent: AgentSpec,
    budget: String,
    seed_first: u64,
    seed_last: u64,
    games: u64,
    /// Searched plies, i.e. total `decisions` across every line — the corpus's
    /// real row count.
    decisions: u64,
    /// Plies that were forced and so carry no label.
    forced_plies: u64,
    policy_recorded: bool,
    /// Replay needs this; see the module docs' recipe.
    engine_rng_salt: String,
    /// Regeneration needs these.
    seat_salts: [String; 2],
    wall_time_s: f64,
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };
    let has = |name: &str| args.iter().any(|a| a == name);

    if has("--help") || args.is_empty() {
        eprintln!(
            "value_corpus_mv: generate an mcts-value search-derived value corpus\n\
             \n\
             generate:  --out <path> [--games N] [--seed S] [--budget nodes:2000]\n\
             \x20          [--params <mcts-value spec params>] [--threads N] [--no-policy]\n\
             verify:    --verify <path> [--sample N]\n"
        );
        return;
    }

    if let Some(path) = flag("--verify") {
        let sample: usize = flag("--sample")
            .map(|s| s.parse().expect("--sample must be a number"))
            .unwrap_or(usize::MAX);
        verify(Path::new(&path), sample);
        return;
    }

    let out = PathBuf::from(flag("--out").expect("--out <path> is required to generate"));
    let games: u64 = flag("--games")
        .map(|s| s.parse().expect("--games must be a number"))
        .unwrap_or(200);
    let seed0: u64 = flag("--seed")
        .map(|s| s.parse().expect("--seed must be a number"))
        .unwrap_or(1);
    let budget_str = flag("--budget").unwrap_or_else(|| "nodes:2000".to_string());
    let budget = parse_budget(&budget_str).expect("a valid --budget");
    let params = flag("--params").unwrap_or_default();
    let cfg = parse_mcts_value_config(&params).expect("valid mcts-value spec params");
    let policy = !has("--no-policy");
    if let Some(t) = flag("--threads") {
        rayon::ThreadPoolBuilder::new()
            .num_threads(t.parse().expect("--threads must be a number"))
            .build_global()
            .expect("the rayon pool is configured once");
    }

    generate(&out, games, seed0, budget, &budget_str, cfg, policy);
}

/// Play one self-play game and return its line.
fn play(seed: u64, budget: Budget, cfg: MctsValueConfig, want_policy: bool) -> GameLine {
    let mut one = MctsValueAgent::with_config(seed ^ SEAT_ONE_SALT, cfg);
    let mut two = MctsValueAgent::with_config(seed ^ SEAT_TWO_SALT, cfg);
    let mut state = engine::new_game(seed);
    let mut rng = StdRng::seed_from_u64(seed ^ ENGINE_RNG_SALT);

    let mut actions: Vec<Action> = Vec::with_capacity(64);
    let mut decisions: Vec<Decision> = Vec::with_capacity(48);

    loop {
        if state.is_over() {
            break;
        }
        // The same order a replay will reconstruct, and the order `chosen` and
        // `policy` are indexed against.
        let legal = engine::legal_actions(&state);
        if legal.is_empty() {
            break;
        }
        let obs = state.observation();
        let mover = state.current_player();
        let agent: &mut MctsValueAgent = match mover {
            Player::One => &mut one,
            Player::Two => &mut two,
        };
        let action = agent.choose(&obs, &legal, budget);
        assert!(
            legal.contains(&action),
            "seed {seed}: agent returned an action outside `legal`: {action:?}"
        );

        // `None` exactly when the move was forced; see `last_root`.
        if let Some(root) = agent.last_root() {
            let chosen = legal
                .iter()
                .position(|&a| a == action)
                .expect("the played action is one of the legal ones");
            let policy = want_policy.then(|| {
                // The readout is in the tree's own shuffled order, so it is
                // re-indexed into `legal_actions` order here — the one order a
                // replay can reproduce.
                legal
                    .iter()
                    .map(|&a| {
                        root.policy
                            .iter()
                            .find(|&&(pa, _)| pa == a)
                            .map(|&(_, n)| n)
                            .unwrap_or(0)
                    })
                    .collect()
            });
            decisions.push(Decision {
                ply: actions.len() as u32,
                mover,
                value: root.value,
                visits: root.visits,
                chosen,
                policy,
            });
        }

        engine::apply(&mut state, action, &mut rng).expect("a legal action applies");
        actions.push(action);
    }

    GameLine {
        seed,
        moves: actions.len() as u32,
        result: state.result().expect("a finished game has a result"),
        actions,
        decisions,
    }
}

fn generate(
    out: &Path,
    games: u64,
    seed0: u64,
    budget: Budget,
    budget_str: &str,
    cfg: MctsValueConfig,
    policy: bool,
) {
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).expect("the output directory is creatable");
    }
    let file = File::create(out).expect("the output file is creatable");
    let mut w = BufWriter::with_capacity(1 << 20, file);

    let spec = MctsValueAgent::with_config(0, cfg).spec();
    println!("agent   {} {}", spec.name, spec.version);
    println!("params  {}", spec.params);
    println!("budget  {budget_str}");
    println!("seeds   {seed0}..{}", seed0 + games);
    println!("out     {}", out.display());
    println!();

    #[allow(clippy::disallowed_methods)]
    let start = std::time::Instant::now();
    let mut total_decisions = 0u64;
    let mut total_forced = 0u64;
    let mut done = 0u64;

    let mpath = manifest_path(out);
    // Rewritten after **every batch**, not once at the end. A full run is
    // hours long, so an interrupted one has to leave a corpus that is still
    // valid and still self-describing — the games already on disk, and a
    // manifest that counts exactly those. Flushing the writer in the same
    // place is what makes the two agree.
    let write_manifest = |games_done: u64, decisions: u64, forced: u64, wall: f64| {
        let manifest = Manifest {
            kind: "duels-value-corpus".to_string(),
            version: 1,
            generated_by: "duels-arena examples/value_corpus_mv.rs".to_string(),
            agent: spec.clone(),
            budget: budget_str.to_string(),
            seed_first: seed0,
            seed_last: seed0 + games_done.max(1) - 1,
            games: games_done,
            decisions,
            forced_plies: forced,
            policy_recorded: policy,
            engine_rng_salt: format!("{ENGINE_RNG_SALT:#018x}"),
            seat_salts: [
                format!("{SEAT_ONE_SALT:#018x}"),
                format!("{SEAT_TWO_SALT:#018x}"),
            ],
            wall_time_s: wall,
        };
        fs::write(
            &mpath,
            serde_json::to_string_pretty(&manifest).expect("the manifest serializes"),
        )
        .expect("the manifest is writable");
    };

    let mut seed = seed0;
    while seed < seed0 + games {
        let end = (seed + BATCH as u64).min(seed0 + games);
        let batch: Vec<GameLine> = (seed..end)
            .into_par_iter()
            .map(|s| play(s, budget, cfg, policy))
            .collect();
        for line in &batch {
            total_decisions += line.decisions.len() as u64;
            total_forced += u64::from(line.moves) - line.decisions.len() as u64;
            serde_json::to_writer(&mut w, line).expect("a game line serializes");
            w.write_all(b"\n").expect("the corpus file is writable");
        }
        done += batch.len() as u64;
        w.flush().expect("the corpus file flushes");
        #[allow(clippy::disallowed_methods)]
        let elapsed = start.elapsed().as_secs_f64();
        write_manifest(done, total_decisions, total_forced, elapsed);
        let rate = done as f64 / elapsed.max(1e-9);
        let eta = (games - done) as f64 / rate.max(1e-9);
        println!(
            "  {done}/{games} games  {total_decisions} decisions  \
             {rate:.1} games/s  eta {:.0} min",
            eta / 60.0
        );
        seed = end;
    }

    #[allow(clippy::disallowed_methods)]
    let wall = start.elapsed().as_secs_f64();
    write_manifest(done, total_decisions, total_forced, wall);

    let bytes = fs::metadata(out).map(|m| m.len()).unwrap_or(0);
    println!();
    println!("wrote   {games} games, {total_decisions} decisions");
    println!("        {} ({:.1} MiB)", out.display(), bytes as f64 / 1e6);
    println!("        {}", mpath.display());
    println!(
        "took    {:.1} min wall ({:.2} s/game/core-equivalent aggregate)",
        wall / 60.0,
        wall / games as f64
    );
}

fn manifest_path(out: &Path) -> PathBuf {
    let mut s = out.as_os_str().to_owned();
    s.push(".manifest.json");
    PathBuf::from(s)
}

/// Replay the corpus against the engine and check every claim it makes, then
/// report whether the recorded values look like win probabilities of the games
/// that actually happened.
///
/// This is the gate the roadmap's "sanity-check before the full run" asks for,
/// and it is deliberately a *replay*: it re-derives every position from
/// `(seed, actions)` and would catch a corpus whose replay key does not
/// reconstruct the game it labelled.
fn verify(path: &Path, sample: usize) {
    let mpath = manifest_path(path);
    match fs::read_to_string(&mpath) {
        Ok(s) => {
            let m: Manifest = serde_json::from_str(&s).expect("the manifest parses");
            println!("manifest {} v{}", m.kind, m.version);
            println!("  agent   {} / {}", m.agent.name, m.agent.params);
            println!("  budget  {}", m.budget);
            println!(
                "  games   {} ({} decisions, {} forced plies), policy={}",
                m.games, m.decisions, m.forced_plies, m.policy_recorded
            );
        }
        Err(e) => println!("(no manifest at {}: {e})", mpath.display()),
    }

    let reader = BufReader::new(File::open(path).expect("the corpus file is readable"));
    let mut games = 0u64;
    let mut rows = 0u64;
    // Paired (recorded value from the mover's view, actual outcome for the
    // mover) for the correlation and the calibration table.
    let mut xs: Vec<f64> = Vec::new();
    let mut ys: Vec<f64> = Vec::new();

    for (i, line) in reader.lines().enumerate() {
        if games as usize >= sample {
            break;
        }
        let line = line.expect("the corpus file reads");
        if line.trim().is_empty() {
            continue;
        }
        let g: GameLine = serde_json::from_str(&line)
            .unwrap_or_else(|e| panic!("line {} does not parse: {e}", i + 1));

        assert_eq!(
            g.moves as usize,
            g.actions.len(),
            "seed {}: moves disagrees with the action list",
            g.seed
        );

        // The replay, exactly as the module docs describe it.
        let mut state = engine::new_game(g.seed);
        let mut rng = StdRng::seed_from_u64(g.seed ^ ENGINE_RNG_SALT);
        let mut next_decision = 0usize;
        for (ply, &action) in g.actions.iter().enumerate() {
            let legal = engine::legal_actions(&state);
            assert!(
                !legal.is_empty(),
                "seed {}: the replay ran out of legal actions at ply {ply}",
                g.seed
            );
            let labelled = g
                .decisions
                .get(next_decision)
                .is_some_and(|d| d.ply as usize == ply);
            if labelled {
                let d = &g.decisions[next_decision];
                next_decision += 1;
                assert!(
                    legal.len() > 1,
                    "seed {}: ply {ply} is labelled but forced",
                    g.seed
                );
                assert_eq!(
                    d.mover,
                    state.current_player(),
                    "seed {}: ply {ply} names the wrong mover",
                    g.seed
                );
                // The load-bearing check: the stored indices really do index
                // this replay's `legal_actions`.
                assert!(
                    d.chosen < legal.len(),
                    "seed {}: ply {ply} chose index {} of {} legal actions",
                    g.seed,
                    d.chosen,
                    legal.len()
                );
                assert_eq!(
                    legal[d.chosen], action,
                    "seed {}: ply {ply}'s chosen index does not name the played action",
                    g.seed
                );
                if let Some(p) = &d.policy {
                    assert_eq!(
                        p.len(),
                        legal.len(),
                        "seed {}: ply {ply}'s policy has the wrong width",
                        g.seed
                    );
                    let top = p.iter().max().copied().unwrap_or(0);
                    assert_eq!(
                        p[d.chosen], top,
                        "seed {}: ply {ply} played a non-argmax action",
                        g.seed
                    );
                }
                assert!(
                    (0.0..=1.0).contains(&d.value),
                    "seed {}: ply {ply}'s value {} is not a probability",
                    g.seed,
                    d.value
                );
                assert!(
                    d.visits > 0,
                    "seed {}: ply {ply} recorded no visits",
                    g.seed
                );
                rows += 1;
            } else {
                assert_eq!(
                    legal.len(),
                    1,
                    "seed {}: ply {ply} had {} legal actions but no label",
                    g.seed,
                    legal.len()
                );
            }
            assert!(
                legal.contains(&action),
                "seed {}: ply {ply}'s action is not legal in the replay",
                g.seed
            );
            engine::apply(&mut state, action, &mut rng)
                .unwrap_or_else(|e| panic!("seed {}: replay failed at ply {ply}: {e}", g.seed));
        }
        assert_eq!(
            next_decision,
            g.decisions.len(),
            "seed {}: {} decisions were never matched to a ply",
            g.seed,
            g.decisions.len() - next_decision
        );

        let replayed = state
            .result()
            .unwrap_or_else(|| panic!("seed {}: the replay did not finish the game", g.seed));
        assert_eq!(
            replayed, g.result,
            "seed {}: the replay reached a different result",
            g.seed
        );

        // Labels against what actually happened, from each mover's own view.
        for d in &g.decisions {
            let outcome = match g.result.winner() {
                None => 0.5,
                Some(w) if w == d.mover => 1.0,
                Some(_) => 0.0,
            };
            let value = match d.mover {
                Player::One => d.value,
                Player::Two => 1.0 - d.value,
            };
            xs.push(value);
            ys.push(outcome);
        }
        games += 1;
    }

    println!();
    println!("replayed {games} games, {rows} labelled decisions — every game reproduced");
    if xs.is_empty() {
        return;
    }
    println!(
        "pearson r(root value, eventual outcome) = {:.4}   brier = {:.4}",
        pearson(&xs, &ys),
        xs.iter()
            .zip(&ys)
            .map(|(x, y)| (x - y) * (x - y))
            .sum::<f64>()
            / xs.len() as f64
    );
    println!();
    println!("  predicted        n     mean outcome");
    for b in 0..10 {
        let lo = b as f64 / 10.0;
        let hi = lo + 0.1;
        let picked: Vec<f64> = xs
            .iter()
            .zip(&ys)
            .filter(|(x, _)| **x >= lo && (**x < hi || (b == 9 && **x <= 1.0)))
            .map(|(_, y)| *y)
            .collect();
        if picked.is_empty() {
            println!("  {lo:.1}-{hi:.1}          0            -");
            continue;
        }
        let mean = picked.iter().sum::<f64>() / picked.len() as f64;
        println!("  {lo:.1}-{hi:.1}   {:>8}          {mean:.3}", picked.len());
    }
}

fn pearson(xs: &[f64], ys: &[f64]) -> f64 {
    let n = xs.len() as f64;
    let mx = xs.iter().sum::<f64>() / n;
    let my = ys.iter().sum::<f64>() / n;
    let mut sxy = 0.0;
    let mut sxx = 0.0;
    let mut syy = 0.0;
    for (x, y) in xs.iter().zip(ys) {
        sxy += (x - mx) * (y - my);
        sxx += (x - mx) * (x - mx);
        syy += (y - my) * (y - my);
    }
    if sxx <= 0.0 || syy <= 0.0 {
        return f64::NAN;
    }
    sxy / (sxx * syy).sqrt()
}
